apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontenddb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddb
spec:
  selector:
    matchLabels:
      app: frontenddb
  template:
    metadata:
      labels:
        app: frontenddb
    spec:
      containers:
        - name: frontenddb
          image: izhengqh/coe692:frontenddb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "student"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: frontenddb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: addcoursedb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addcoursedb
spec:
  selector:
    matchLabels:
      app: addcoursedb
  template:
    metadata:
      labels:
        app: addcoursedb
    spec:
      containers:
        - name: addcoursedb
          image: izhengqh/coe692:addcoursedb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "student"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: addcoursedb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registercoursedb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registercoursedb
spec:
  selector:
    matchLabels:
      app: registercoursedb
  template:
    metadata:
      labels:
        app: registercoursedb
    spec:
      containers:
        - name: registercoursedb
          image: izhengqh/coe692:registercoursedb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "student"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: registercoursedb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addcoursesservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addcoursesservice
  template:
    metadata:
      labels:
        app: addcoursesservice
    spec:
      containers:
        - name: addcoursesservice
          image: izhengqh/coe692:addcoursesservice
          ports:
            - containerPort: 8080
          env:
            - name: ADDCOURSE_DB_HOST
              value: addcoursedb
            - name: ADDCOURSE_DB_PORT
              value: "3306"
            - name: ADDCOURSE_DB_NAME
              value: addCourse_LBS
            - name: ADDCOURSE_DB_USER
              value: root
            - name: ADDCOURSE_DB_PASSWORD
              value: student
            - name: kubeMQAddress
              value: kubemq-cluster-grpc.kubemq:50000
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registercoursesservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registercoursesservice
  template:
    metadata:
      labels:
        app: registercoursesservice
    spec:
      containers:
        - name: registercoursesservice
          image: izhengqh/coe692:registercoursesservice
          ports:
            - containerPort: 8080
          env:
            - name: REGCOURSE_DB_HOST
              value: registercoursedb
            - name: REGCOURSE_DB_PORT
              value: "3306"
            - name: REGCOURSE_DB_NAME
              value: regCourse_LBS
            - name: REGCOURSE_DB_USER
              value: root
            - name: REGCOURSE_DB_PASSWORD
              value: student
            - name: kubeMQAddress
              value: kubemq-cluster-grpc.kubemq:50000
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendservice
  template:
    metadata:
      labels:
        app: frontendservice
    spec:
      containers:
        - name: frontendservice
          image: izhengqh/coe692:frontendservice
          ports:
            - containerPort: 8080
          env:
            - name: FRONTEND_DB_HOST
              value: frontenddb
            - name: FRONTEND_DB_PORT
              value: "3306"
            - name: FRONTEND_DB_NAME
              value: frontend_auth
            - name: FRONTEND_DB_USER
              value: root
            - name: FRONTEND_DB_PASSWORD
              value: student
            - name: ADDCOURSE_SERVICE_HOST
              value: addcoursesservice
            - name: ADDCOURSE_SERVICE_PORT
              value: "80"
            - name: REGCOURSE_SERVICE_HOST
              value: registercoursesservice
            - name: REGCOURSE_SERVICE_PORT
              value: "80"
          imagePullPolicy: Always
